---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          args: [ "server", "/data", "--console-address", ":9001" ]
          command: [ "minio" ]
          env:
            - name: MINIO_ROOT_USER
              value: "SECRETUSER"
            - name: MINIO_ROOT_PASSWORD
              value: "really/secure/pass"
          image: quay.io/minio/minio
          ports:
            - containerPort: 9000
            - containerPort: 9001
