apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: "9000"
      protocol: TCP
      port: 9000
    - name: "console"
      protocol: TCP
      port: 9001
