---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sogno-file-service
spec:
  selector:
    matchLabels:
      app: sogno-file-service
  template:
    metadata:
      labels:
        app: sogno-file-service
    spec:
      containers:
        - name: sogno-file-service
          image: sogno/file-service
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root-password
              
  

---
apiVersion: v1
kind: Service
metadata:
  name: sogno-file-service
spec:
  selector:
    app: sogno-file-service
  type: NodePort
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
